config/routes.rb
Rails.application.routes.draw do

  resources :cocktails, only: [:index, :show, :new, :create, :destroy] do
    resources :doses, only: [:new, :create]
  end

  resources :doses, only: [:destroy]

  root to: 'cocktails#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true

  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, presence: true, uniqueness: { scope: :ingredient }
  validates :ingredient, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def home
  end

  def index
    @cocktails = Cocktail.all
  end
  def show
    @cocktail = Cocktail.find(params[:id])
  end
  def new
    @cocktail = Cocktail.new
  end
  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.save
    redirect_to cocktails_path
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @dose = Dose.new
    @ingredients = Ingredient.all
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @ingredient = Ingredient.find(params[:dose][:ingredient])
    @dose = Dose.new(doses_params)
    @dose.cocktail = @cocktail
    @dose.ingredient = @ingredient
    @dose.save
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def doses_params
    params.require(:dose).permit(:description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/home.html.erb
<div class="active-banner-js">

  <%= render './shared/home_banner' %>




<%= cl_image_tag("banner_cocktails",
      width: 400, height: 300, crop: :fill) %>
  <% 100.times do %>
    <p>Hello</p>
  <% end %>



</div>

app/views/cocktails/index.html.erb
<div class="container">
  <h1>All the cocktails</h1>



  <div class="row">
    <ul class="list-unstyled">
      <% @cocktails.each do |cocktail| %>
        <div class="col-xs-12 col-sm-4">
          <li>
            <div class="card" style="background-image: url('<%= cl_image_path @cocktail.photo, height: 300, width: 400, crop: :fill %>')">
              <div class="cocktail-delete"><%= link_to 'Delete', cocktail_path(cocktail), method: :delete %></div>
              <div class="cocktail-name"><%= link_to cocktail.name, cocktail_path(cocktail), class: "text-center" %></div>
            </div>
          </li>
        </div>
      <% end %>
    </ul>
  </div>



   <%#= render './shared/create_cocktail_modal' %>


  <%= link_to 'Create a cocktail', new_cocktail_path %>

</div>

app/views/cocktails/new.html.erb
<div class="container">
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.button :submit %>
  <% end %>

<%= link_to 'Back home', cocktails_path %>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <h1><%= @cocktail.name %></h1>

  <p>Ingredients :</p>

  <ul>
    <% @cocktail.doses.each do |dose| %>
      <li>
        <%=dose.ingredient.name%> - <%= dose.description %>
        <%= link_to 'Delete', dose_path(dose), method: :delete %>
      </li>
    <% end %>
  </ul>

  <%= link_to 'Add a dose', new_cocktail_dose_path(@cocktail) %>

  <%= link_to 'Back home', cocktails_path %>
</div>

app/views/doses/new.html.erb
<div class="container">
  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description %>
    <%= f.input :ingredient, as: :select, collection: @ingredients %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_page?('/') %>
      <%= render './shared/navbar_home' %>
    <% else %>
      <%= render './shared/navbar' %>
    <% end %>

    <%= yield %>




    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>

app/views/shared/_create_cocktail_modal.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
  Create a new cocktail
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Create your cocktail</h4>
      </div>
      <div class="modal-body">

        <%= simple_form_for Cocktail.new do |f| %>
          <%= f.input :name %>
          <%= f.submit %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_home_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://res.cloudinary.com/dshrp2jtn/image/upload/v1526659181/banner_cocktails.jpg');">
  <div class="banner-content">
    <h1>Cocktails creator</h1>
    <p><span id="banner-typed-text"></span></p>
    <%= link_to "Start now", cocktails_path, class: "btn btn-primary btn-lg"%>


  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-white">
  <!-- Logo -->
  <%= link_to 'Home', root_path %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">



    <%= render './shared/create_cocktail_modal' %>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_home.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <span></span>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <a href="" class="navbar-wagon-item navbar-wagon-link">Host</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link">Trips</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link">Messages</a>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div>
</div>